---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Packer
      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      # Initialize Packer
      - name: Init Packer
        run: |
          cd hashidemos && packer init .

      # Build!
      - name: Build Packer
        run: |
          echo $HCP_CLIENT_ID
          cd hashidemos && packer build -var 'aws_packer_role=${{ secrets.AWS_PACKER_ROLE }}' .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_EXPIRATION: ${{ secrets.AWS_SESSION_EXPIRATION }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
